/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportation;

import Account.UIS;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Duygu-Alperen
 */
public class PlaneTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlaneTicket
     */
    public PlaneTicketFrame() {
        initComponents();
        ImageIcon planeTicketBg=new ImageIcon("Images/planeTicket.png");
       ticketBg.setIcon(planeTicketBg);
       
       ImageIcon logo=new ImageIcon("Images/logo.png");
        logoLabel.setIcon(logo);
       
      
       int userIndex = UIS.checkAccountIndex(Loginn.usernameTextField.getText());
       int ticketIndex = UIS.ticketCheck(PlaneTicketBooking.fromBox.getSelectedItem().toString());
       
       
       fromLabel.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).fromCountry);
       toLabel.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).toCountry);
       dateLabel.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).departing);
       departureLabel.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).departingTime);
       if(PlaneSit.economyRb.isSelected()){
           seatLabel.setText(PlaneSit.ecoSeatNumBox.getSelectedItem().toString()+PlaneSit.ecoSeatAlphaBox.getSelectedItem().toString());
       }
       
       else{
           seatLabel.setText(PlaneSit.preNumericalBox.getSelectedItem().toString()+PlaneSit.preAlphBox.getSelectedItem().toString());
       }
       priceLabel.setText(String.valueOf(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).ticketPrice));
       
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        seatLabel = new javax.swing.JLabel();
        departureLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        ticketBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FROM:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel2.setText("TO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setText("DATE:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));
        jPanel2.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 100));

        jLabel4.setText("DEPARTURE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel8.setText("SEAT");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));
        jPanel2.add(seatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 40));
        jPanel2.add(departureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, 20));
        jPanel2.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 20));
        jPanel2.add(toLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, 20));
        jPanel2.add(fromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 90, 20));

        jLabel5.setText("PRICE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        jPanel2.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 90, 20));
        jPanel2.add(ticketBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaneTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaneTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaneTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaneTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaneTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel seatLabel;
    private javax.swing.JLabel ticketBg;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
