/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportation;

import Account.UIS;
import javax.swing.ImageIcon;

/**
 *
 * @author Duygu-Alperen
 */
public class Tickets extends javax.swing.JFrame {

    /**
     * Creates new form Tickets
     */
    public Tickets() {
        initComponents();
           ticketTa.setVisible(false);
           ticketTa.setEditable(false);
           
        ImageIcon backicon = new ImageIcon("Images/backicon.png");
        backiconLabel.setIcon(backicon);
        
        ImageIcon usernameicon = new ImageIcon("Images/usernameicon.png");
        userLabel.setIcon(usernameicon);
        userPanel.setVisible(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        changeLabel = new javax.swing.JLabel();
        faqLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketTa = new javax.swing.JTextArea();
        showButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        backiconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateCheck = new com.toedter.calendar.JDateChooser();
        searchButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        changeLabel.setText("Change xx");
        changeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeLabelMouseExited(evt);
            }
        });

        faqLabel.setText("F.A.Q");
        faqLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faqLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faqLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faqLabelMouseExited(evt);
            }
        });

        outLabel.setText("Sign Out");
        outLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(changeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faqLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 120, 110));

        ticketTa.setColumns(20);
        ticketTa.setRows(5);
        jScrollPane2.setViewportView(ticketTa);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 570, 330));

        showButton.setText("Show Tickets");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });
        jPanel1.add(showButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 30, 30));

        backiconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backiconLabelMouseClicked(evt);
            }
        });
        jPanel1.add(backiconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 30));

        jLabel1.setText("Search Specicif Ticket Time");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, -1));
        jPanel1.add(dateCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, -1));

        searchButton.setText("Search It");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        deleteButton.setText("Delete it");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String dateToString(){
        String date = "";
        int month = dateCheck.getDate().getMonth();
        int year = dateCheck.getDate().getYear();
        int day = dateCheck.getDate().getDate();
        date = String.valueOf(day) +"/" +String.valueOf(month+1) +"/"+ String.valueOf(year+1900);
        return date;
    }
    
    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        ticketTa.setVisible(true);
        int userIndex = UIS.checkAccountIndex(Loginn.usernameTextField.getText());
        String output = "";
        for(int i=0;i<UIS.accounts.get(userIndex).getUserTickets().size();i++){
            output += UIS.accounts.get(userIndex).getUserTickets().get(i).toString();
            System.out.println(UIS.accounts.get(userIndex).getUserTickets().get(i).toString());
        }
        ticketTa.setText(output);
    }//GEN-LAST:event_showButtonActionPerformed

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        if(userPanel.isVisible()){
            userPanel.setVisible(false);
        }
        else
        userPanel.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_userLabelMouseClicked

    private void backiconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backiconLabelMouseClicked
       this.dispose(); 
    // TODO add your handling code here:
    }//GEN-LAST:event_backiconLabelMouseClicked

    private void changeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseClicked
        PersonalInformation subFrame = new PersonalInformation();
        subFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseClicked

    private void changeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseEntered
        changeLabel.setText("<HTML><U>Change xx</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseEntered

    private void changeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseExited
        changeLabel.setText("<HTML>Change xx</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseExited

    private void faqLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseClicked
        FAQ subFrame = new FAQ();
        subFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseClicked

    private void faqLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseEntered
        faqLabel.setText("<HTML><U>F.A.Q</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseEntered

    private void faqLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseExited
        faqLabel.setText("<HTML>F.A.Q</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseExited

    private void outLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseClicked
        Loginn subFrame=new Loginn();
        subFrame.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseClicked

    private void outLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseEntered
        outLabel.setText("<HTML><U>Sign Out</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseEntered

    private void outLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseExited
        outLabel.setText("<HTML>Sign Out</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseExited

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        ticketTa.setVisible(true);
        String mydate = dateToString();
        
        String allticket = UIS.searchDatedTicket(mydate);
        
        ticketTa.setText(allticket);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ticketTa.setVisible(true);
        String mydate = dateToString();
        UIS.deleteDatedTicket(mydate);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backiconLabel;
    private javax.swing.JLabel changeLabel;
    private com.toedter.calendar.JDateChooser dateCheck;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel faqLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel outLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showButton;
    private javax.swing.JTextArea ticketTa;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
