/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportation;

import Account.UIS;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Duygu-Alperen
 */
public class TrainTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrainTicket
     */
    public TrainTicketFrame() {
        initComponents();
        
        ImageIcon logo=new ImageIcon("Images/logo.png");
        logoLabel.setIcon(logo);
        ImageIcon background=new ImageIcon("Images/trainTicket.jpg");
        backgroundLabel.setIcon(background);
        
       int userIndex = UIS.checkAccountIndex(Loginn.usernameTextField.getText());
       int ticketIndex = UIS.ticketCheck(TrainTicketBooking.fromBox.getSelectedItem().toString());
       
       fromLabel1.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).fromCountry);

       toLabel1.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).toCountry);

       dateLabel1.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).departing);

       departureLabel1.setText(UIS.accounts.get(userIndex).getUserTickets().get(ticketIndex).departingTime);
       
       wagonLabel.setText(TrainTicketBooking.wagonNoBox.getSelectedItem().toString());
       if(TrainTicketBooking.isBeddedCheck.isSelected()){
           cabinTypeLabel.setText("Bedded Cabin");
       }
       else{
           cabinTypeLabel.setText("Normal Cabin");
       }
       
       
   
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fromLabel1 = new javax.swing.JLabel();
        toLabel1 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        departureLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        wagonLabel = new javax.swing.JLabel();
        wagonNo = new javax.swing.JLabel();
        cabinTypeLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("FROM:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setText("TO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel8.setText("DATE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        jLabel9.setText("DEPARTURE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));
        jPanel1.add(fromLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 20));
        jPanel1.add(toLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, 20));
        jPanel1.add(dateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 120, 20));
        jPanel1.add(departureLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 20));

        jLabel1.setText("CABIN TYPE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, -1));

        wagonLabel.setText("WAGON:");
        jPanel1.add(wagonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, -1));
        jPanel1.add(wagonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, 20));
        jPanel1.add(cabinTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 20));
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, 100));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 520, 250));
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 510, 230));

        jLabel3.setText(".");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel cabinTypeLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JLabel departureLabel1;
    private javax.swing.JLabel fromLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel toLabel1;
    private javax.swing.JLabel wagonLabel;
    private javax.swing.JLabel wagonNo;
    // End of variables declaration//GEN-END:variables
}
