/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportation;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Media;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author Duygu-Alperen
 */
public class Transportations extends javax.swing.JFrame {
    Clip clip;
    /**
     * Creates new form Transportations
     */
    public Transportations() {
        initComponents();
        
        
        
        ImageIcon planeBg = new ImageIcon("Images/flight.png");
        planeBgLabel.setIcon(planeBg);
        ImageIcon trainBg = new ImageIcon("Images/train.png");
        trainBgLabel.setIcon(trainBg);
        ImageIcon shipBg = new ImageIcon("Images/ship.png");
        shipBgLabel.setIcon(shipBg);
        
        ImageIcon backicon = new ImageIcon("Images/backicon.png");
        backıconLabel.setIcon(backicon);
        
        ImageIcon usernameicon = new ImageIcon("Images/usernameicon.png");
        userLabel.setIcon(usernameicon);
        
        userPanel.setVisible(false);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
    public boolean flag = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        trainBgLabel = new javax.swing.JLabel();
        ShipPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        shipBgLabel = new javax.swing.JLabel();
        PlanePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        planeBgLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        backıconLabel = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        ticketLabel = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        faqLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TrainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 20)); // NOI18N
        jLabel4.setText("Train");
        TrainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 68, 90, -1));

        trainBgLabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 20)); // NOI18N
        trainBgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainBgLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trainBgLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trainBgLabelMouseExited(evt);
            }
        });
        TrainPanel.add(trainBgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 180));

        getContentPane().add(TrainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 180));

        ShipPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 20)); // NOI18N
        jLabel5.setText("Ship");
        ShipPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 90, 80, -1));

        shipBgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shipBgLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shipBgLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shipBgLabelMouseExited(evt);
            }
        });
        ShipPanel.add(shipBgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 190));

        getContentPane().add(ShipPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 550, 190));

        PlanePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlanePanelMouseEntered(evt);
            }
        });
        PlanePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 20)); // NOI18N
        jLabel3.setText("Plane");
        PlanePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 66, 80, -1));

        planeBgLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planeBgLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                planeBgLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                planeBgLabelMouseExited(evt);
            }
        });
        PlanePanel.add(planeBgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 180));

        getContentPane().add(PlanePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 180));

        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        backıconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backıconLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(backıconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backıconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userLabel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 50));

        ticketLabel.setText("My Tickets");
        ticketLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ticketLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ticketLabelMouseExited(evt);
            }
        });

        changeLabel.setText("Change xx");
        changeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeLabelMouseExited(evt);
            }
        });

        faqLabel.setText("F.A.Q");
        faqLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faqLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faqLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faqLabelMouseExited(evt);
            }
        });

        outLabel.setText("Sign Out");
        outLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faqLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ticketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faqLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 120, 130));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 4, 250, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlanePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlanePanelMouseEntered

        
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanePanelMouseEntered

    private void trainBgLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainBgLabelMouseEntered
        // TODO add your handling code here:
        ImageIcon trainGif = new ImageIcon("Images/traingif.gif");
        trainBgLabel.setIcon(trainGif);
        trainAudioPlay();
    }//GEN-LAST:event_trainBgLabelMouseEntered

    private void trainBgLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainBgLabelMouseExited
        // TODO add your handling code here:
        clip.stop();
        ImageIcon trainBg = new ImageIcon("Images/train.png");
        trainBgLabel.setIcon(trainBg);
    }//GEN-LAST:event_trainBgLabelMouseExited

    private void shipBgLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipBgLabelMouseEntered
        // TODO add your handling code here:
        ImageIcon shipGif = new ImageIcon("Images/shipgif.gif");
        shipBgLabel.setIcon(shipGif);
        shipAudioPlay();
    }//GEN-LAST:event_shipBgLabelMouseEntered

    private void shipBgLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipBgLabelMouseExited
        // TODO add your handling code here:
        clip.stop();
        ImageIcon shipBg = new ImageIcon("Images/ship.png");
        shipBgLabel.setIcon(shipBg);
    }//GEN-LAST:event_shipBgLabelMouseExited

    private void planeBgLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planeBgLabelMouseExited
        // TODO add your handling code here:
        clip.stop();
        ImageIcon planeBg = new ImageIcon("Images/flight.png");
        planeBgLabel.setIcon(planeBg);
        
    }//GEN-LAST:event_planeBgLabelMouseExited

    private void planeBgLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planeBgLabelMouseEntered
        // TODO add your handling code here:
        ImageIcon planeBg = new ImageIcon("Images/planegif.gif");
        planeBgLabel.setIcon(planeBg);
        planeAudioPlay();

    }//GEN-LAST:event_planeBgLabelMouseEntered

    private void backıconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backıconLabelMouseClicked
 
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backıconLabelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        if(userPanel.isVisible()){
            userPanel.setVisible(false);
        }
        else
        userPanel.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_userLabelMouseClicked

    private void planeBgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planeBgLabelMouseClicked
        // TODO add your handling code here:
        PlaneTicketBooking planeTicketBooking = new PlaneTicketBooking();
        planeTicketBooking.setVisible(true);
    }//GEN-LAST:event_planeBgLabelMouseClicked

    private void trainBgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainBgLabelMouseClicked
        // TODO add your handling code here:
        TrainTicketBooking trainTicketBooking = new TrainTicketBooking();
        trainTicketBooking.setVisible(true);
    }//GEN-LAST:event_trainBgLabelMouseClicked

    private void shipBgLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipBgLabelMouseClicked
         // TODO add your handling code here:
         ShipTicketBooking shipTicketBooking= new ShipTicketBooking();
         shipTicketBooking.setVisible(true);
    }//GEN-LAST:event_shipBgLabelMouseClicked

    private void ticketLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseClicked
        // TODO add your handling code here:
        Tickets subTickets = new Tickets();
        subTickets.setVisible(true);
    }//GEN-LAST:event_ticketLabelMouseClicked

    private void ticketLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseEntered
        ticketLabel.setText("<HTML><U>My Tickets</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketLabelMouseEntered

    private void ticketLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketLabelMouseExited
        ticketLabel.setText("<HTML>My Tickets</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketLabelMouseExited

    private void changeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseClicked
        PersonalInformation subFrame = new PersonalInformation();
        subFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseClicked

    private void changeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseEntered
        changeLabel.setText("<HTML><U>Change xx</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseEntered

    private void changeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLabelMouseExited
        changeLabel.setText("<HTML>Change xx</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLabelMouseExited

    private void faqLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseClicked
        FAQ subFrame = new FAQ();
        subFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseClicked

    private void faqLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseEntered
        faqLabel.setText("<HTML><U>F.A.Q</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseEntered

    private void faqLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faqLabelMouseExited
        faqLabel.setText("<HTML>F.A.Q</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_faqLabelMouseExited

    private void outLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseClicked
        Loginn subFrame=new Loginn();
        subFrame.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseClicked

    private void outLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseEntered
        outLabel.setText("<HTML><U>Sign Out</U></HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseEntered

    private void outLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outLabelMouseExited
        outLabel.setText("<HTML>Sign Out</HTML>");
        // TODO add your handling code here:
    }//GEN-LAST:event_outLabelMouseExited
    public void planeAudioPlay(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("Audios/planeAudio.wav"));
            clip = AudioSystem.getClip();
            clip.open(stream);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void shipAudioPlay(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("Audios/shipAudio.wav"));
            clip = AudioSystem.getClip();
            clip.open(stream);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void trainAudioPlay(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("Audios/trainAudio.wav"));
            clip = AudioSystem.getClip();
            clip.open(stream);
            clip.start();

        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Transportations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transportations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transportations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transportations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transportations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transportations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlanePanel;
    private javax.swing.JPanel ShipPanel;
    private javax.swing.JPanel TrainPanel;
    private javax.swing.JLabel backıconLabel;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel faqLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel outLabel;
    public javax.swing.JLabel planeBgLabel;
    private javax.swing.JLabel shipBgLabel;
    private javax.swing.JLabel ticketLabel;
    private javax.swing.JLabel trainBgLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
